version: '3.8'

services:
  shortliner-analytics:
    build: .
    container_name: shortliner-analytics-app
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    networks:
      - shortliner-net


networks:
  shortliner-net:
    external: true