CREATE TABLE aggregated_stats
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    short_code      VARCHAR(20) NOT NULL,
    stats_date      DATE        NOT NULL,
    click_count     BIGINT      NOT NULL DEFAULT 0,
    unique_visitors BIGINT      NOT NULL DEFAULT 0,
    last_updated    TIMESTAMP   NOT NULL,

    CONSTRAINT pk_aggregated_stats PRIMARY KEY (id),
    CONSTRAINT uk_short_code_date UNIQUE (short_code, stats_date)
);

CREATE INDEX idx_stats_short_code ON aggregated_stats (short_code);
